openapi: "3.0.3"
info:
  title: "Allocation API"
  description: "Backend application for resources allocation system"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
    description: "Local server"

tags:
  - name: "User"
    description: "Operations on users"
  - name: "Demand"
    description: "Operations on requests"
  - name: "Resource"
    description: "Operations on resources"
paths:
  /auth/signup:
    post:
      tags:
        - "User"
      summary: "Create an account"
      description: "Create an endpoint for signing up the users"
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequestDTO'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponseDTO'
        '403':
          description: Forbidden access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenAccessDTO'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestDTO'
  /user/{id}:
    patch:
      tags:
        - "User"
      description: "Create an endpoint for updating a user"
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          description: "The id of the user to update"
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequestDTO'
      responses:
        '200':
          description: "User updated successfully"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /users:
    get:
      tags:
        - "User"
      description: "Get all users"
      operationId: getAllUsers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /users/{id}:
    get:
      tags:
        - "User"
      description: "Get a user by its id"
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          description: "The id of the user to get"
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /users/delete/{id}:
      delete:
        tags:
          - "User"
        description: "Delete a user"
        operationId: deleteUser
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
        responses:
          '200':
            description: "User deleted successfully"
          '404':
              description: "Not Found"
  /createrequest:
    post:
      tags:
        - "Demand"
      summary: "Create a demand"
      description: "Create an endpoint for registering a demand"
      operationId: createDemand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDemandRequestDTO'
      responses:
        '200':
          description: "Request created successfully"
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestDTO'
  /requests:
      get:
        tags:
          - "Demand"
        summary: "Get all demands"
        description: "Create an endpoint to get all the demands"
        operationId: getAllDemands
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/DemandDTO'
          '404':
            description: Not found
  /request/{id}:
    patch:
      tags:
        - "Demand"
      summary: "Update a demand"
      description: "Create an endpoint to update a demand"
      operationId: updateDemand
      parameters:
        - name: id
          in: path
          required: true
          description: "The id of the user to update"
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDemandDTO'
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
  /requests/delete/{id}:
    delete:
      tags:
        - "Demand"
      summary: "Delete a demand"
      description: "Create an endpoint to delete a demand"
      operationId: deleteDemand
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Demand deleted successfully"
        '404':
          description: "Not Found"
  /createresource:
    post:
      tags:
        - "Resource"
      summary: "Create a resource"
      description: "Create and endpoint to add a new resource"
      operationId: createResource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateResourceRequestDTO'
      responses:
        '200':
          description: "Resource created successfully"
        '400':
          description: "Bad Request"
  /resources:
    get:
      tags:
        - "Resource"
      summary: "Get all resources"
      description: "Get the list of all the resources"
      operationId: getAllResources
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceDTO'
        '404':
          description: Not found
  /resources/{id}:
    get:
      tags:
        - "Resource"
      summary: "Get a resource"
      description: "Create an endpoint to get a resource by its id"
      operationId: getResource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceDTO'
        '404':
          description: Not found
  /resource/{id}:
    patch:
      tags:
        - "Resource"
      summary: "Update a resource"
      description: "Create an endpoint to update a resource"
      operationId: updateResource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceDTO'
      responses:
        '200':
          description: Success
        '404':
          description: Not found
  /resources/delete/{id}:
    delete:
      tags:
        - "Resource"
      summary: "Delete a resource"
      description: "Create an endpoint to delete a resource"
      operationId: deleteResource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Resource deleted successfully"
        '404':
          description: "Not Found"











components:
  schemas:
    AuthenticationRequestDTO:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "user@entreprise.com"
        password:
          type: string
          format: password

    AuthenticationResponseDTO:
      type: object
      properties:
        token:
          type: string
        isAdmin:
          type: boolean
          example: true

    ErrorDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
          example: "Invalid credentials"

    SignupRequestDTO:
      type: object
      required:
        - name
        - surname
        - email
      properties:
        name:
          type: string
          example: "name"
        surname:
          type: string
          example: "surname"
        email:
          type: string
          format: email
          example: "user@entreprise.com"

    SignupResponseDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
          example: "User created successfully"

    ForbiddenAccessDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
          example: "User has not access"

    BadRequestDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
          example: "Invalid data"


    UpdateUserRequestDTO:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        surname:
          type: string

    UserDTO:
     type: object
     properties:
       id:
          type: integer
          format: int64
       name:
          type: string
       surname:
          type: string
       email:
          type: string

    CreateDemandRequestDTO:
     type: object
     properties:
       resource_name:
         type: string
       quantity:
         type: string
       description:
         type: string
       justification:
         type: string
       urgency:
         type: string
       due_date:
         type: string

    DemandDTO:
      type: object
      properties:
        id:
          type: integer
        user_name:
          type: string
        user_email:
          type: string
        resource_name:
          type: string
        description:
          type: string
        justification:
          type: string
        urgency:
          type: string
        due_date:
          type: string
        quantity:
          type: string
        status:
          type: string
        date_time:
          type: string

    UpdateDemandDTO:
      type: object
      properties:
        user_name:
          type: string
        user_email:
          type: string
        resource_name:
          type: string
        description:
          type: string
        justification:
          type: string
        urgency:
          type: string
        due_date:
          type: string
        quantity:
          type: string
        status:
          type: string

    CreateResourceRequestDTO:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        description:
          type: string
        isAvailable:
          type: boolean

    ResourceDTO:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        description:
          type: string
        isAvailable:
          type: boolean



















